#
# config.mk
#
# Product-specific compile-time definitions.
#

BOARD_USES_QCOM_HARDWARE := true
DYNAMIC_SHARED_LIBV8SO := true
BOARD_USES_ADRENO_200 := true
HAVE_ADRENO200_SOURCE := true
HAVE_ADRENO200_SC_SOURCE := true
HAVE_ADRENO200_FIRMWARE := true
BOARD_USES_QCNE := true
USE_OPENGL_RENDERER := true
BOARD_USE_QCOM_LLVM_CLANG_RS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := msm7627a
BOARD_HAVE_BLUETOOTH := true
USE_CAMERA_STUB := true
TARGET_HAVE_TSLIB := true
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false
TARGET_NO_RADIOIMAGE := true
TARGET_GRALLOC_USES_ASHMEM := true
TARGET_CPU_ABI  := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_BOARD_PLATFORM := msm7627a
TARGET_BOOTLOADER_BOARD_NAME := pico
TARGET_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true
QCOM_TARGET_PRODUCT := msm7627a
TARGET_CORTEX_CACHE_LINE_32 := true
TARGET_USE_SPARROW_BIONIC_OPTIMIZATION := true
TARGET_USES_UNCOMPRESSED_KERNEL := false
ARCH_ARM_HAVE_TLS_REGISTER := true
BOARD_NO_SPEAKER := true
BOARD_NO_TOUCHSCREEN := false
BOARD_HAVE_MXT224_CFG := true
